---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

commonLabels:
  app.kubernetes.io/name: etcd

images:
  - name: etcd-server
    newName: quay.io/coreos/etcd
    newTag: "v3.4.15"

...
