---
apiVersion: v1
kind: Service

metadata:
  name: etcd-hl
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true

  ports:
    - name: client
      port: 2379
    - name: server
      port: 2380

...
