---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: etcd-server
    options:
      labels:
        app.kubernetes.io/name: etcd
        app.kubernetes.io/component: server
    literals: []

secretGenerator:
  - name: etcd-server
    options:
      labels:
        app.kubernetes.io/name: etcd
        app.kubernetes.io/component: server
    literals: []

images:
  - name: etcd-server
    newName: quay.io/coreos/etcd
    newTag: "v3.5.16"

...
