---
apiVersion: v1
kind: Service

metadata:
  name: etcd-server
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/component: server
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

spec:
  publishNotReadyAddresses: true

  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/component: server

  ports:
    - name: client
      port: 2379
    - name: server
      port: 2380

...
